artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Alvarho/Data/raw/main/images.zip
  local_data_file: artifacts/data_ingestion/images.zip
  unzip_dir: artifacts/data_ingestion